build(deps): bump jetty.version from 12.0.22 to 12.0.23 (#991)
Bumps `jetty.version` from 12.0.22 to 12.0.23.
Updates `org.eclipse.jetty:jetty-bom` from 12.0.22 to 12.0.23
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/jetty/jetty.project/releases">org.eclipse.jetty:jetty-bom's
releases</a>.</em></p>
<blockquote>
<h2>12.0.23</h2>
<h1>Special Thanks to the following Eclipse Jetty community members</h1>
<ul>
<li><a
href="https://github.com/maarouf-yassine"><code>@​maarouf-yassine</code></a>
(Maarouf Yassine)</li>
<li><a
href="https://github.com/kohlschuetter"><code>@​kohlschuetter</code></a>
(Dr. Christian Kohlschütter)</li>
</ul>
<h1>Changelog</h1>
<ul>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13303">#13303</a>
- Improved logging and exception handling in HTTP2Producer.</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13300">#13300</a>
- <code>o.e.j.plus.jndi.Resource</code>s declared in <code>eeX</code>
scope then linked via <code>&lt;resource-ref&gt;</code> or
<code>&lt;resource-env-ref&gt;</code> in web.xml not found</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13299">#13299</a>
- Race Condition in WebSocketConnection - Job failed:
java.lang.IllegalStateException: FILLING_AND_PARSING</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13274">#13274</a>
- 13287 Make <code>Environment</code> implementation thread-safe to
prevent <code>ConcurrentModificationException</code></li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13268">#13268</a>
- <code>charset=null</code> is automatically added when using
<code>Content-Type: application/problem+json</code> in Servlet ee10</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13266">#13266</a>
- Fix Typo in http.adoc (<a
href="https://github.com/maarouf-yassine"><code>@​maarouf-yassine</code></a>)</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13263">#13263</a>
- NPE from SslEndPoint.isInputShutdown</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13261">#13261</a>
- Improve handling of failed HTTP/2 requests</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13259">#13259</a>
- <code>org.eclipse.jetty.plus.jndi.Transaction</code> should support
<code>javax.naming.Referenceable</code> as a constructor option
too.</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13234">#13234</a>
- Regression in 12.0.21 on handling empty query parameters</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13232">#13232</a>
- Regression in ee9/ee8 getRequestDispatcher() exceptions</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13209">#13209</a>
- stop throwing ISE when complete() is called after abort()</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13201">#13201</a>
- Fix <code>ReadPendingException</code> warning</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13196">#13196</a>
- Download of large file may get stuck in an infinite loop (bug in
<code>IOResources.copy</code> / <code>Content.Source</code>) (<a
href="https://github.com/kohlschuetter"><code>@​kohlschuetter</code></a>)</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13190">#13190</a>
- Introduce ability to decode and/or canonicalize URIs in a
RewriteRule</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/12818">#12818</a>
- NPE with websocket java.lang.NullPointerException: Cannot invoke
&quot;org.eclipse.jetty.io.RetainableByteBuffer.hasRemaining()&quot;
because &quot;this.networkBuffer&quot; is null</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/jetty/jetty.project/commit/01a4119797e9cee53c974ae126cc316d0c8a533a"><code>01a4119</code></a>
Updating to version 12.0.23</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/030d5867e4562428103361b7d6e987f0707e3831"><code>030d586</code></a>
Fixing typo in release script</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/5ac211ce5abceb094255c3e802a7ea4189f2cc86"><code>5ac211c</code></a>
Race Condition in WebSocketConnection - Job failed:
java.lang.IllegalStateExc...</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/a5dcbd0df7925f55ffef9946e6aa4e46dafcfec9"><code>a5dcbd0</code></a>
Merge pull request <a
href="https://redirect.github.com/jetty/jetty.project/issues/13303">#13303</a>
from jetty/fix/jetty-12.0.x/improve-h2-producer-exc...</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/5b5f82d740dadf9f95f51c12c1e2d6500cd145c9"><code>5b5f82d</code></a>
Rework locked fields accesses in <code>SslConnection</code> (<a
href="https://redirect.github.com/jetty/jetty.project/issues/13265">#13265</a>)</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/87f982c9964117b36b4ff0d8278811013e97381a"><code>87f982c</code></a>
Merge pull request <a
href="https://redirect.github.com/jetty/jetty.project/issues/13301">#13301</a>
from jetty/jetty-12.0.x-13300-resource-ee-namespace</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/e179ee3a467e7f0793fa032ae92c47827f75ed6e"><code>e179ee3</code></a>
upgrade quiche to version 0.24.4</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/6d3f29260a40e669041293b1b18da3c9acf45017"><code>6d3f292</code></a>
Improved logging and exception handling in HTTP2Producer.</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/05110ba7c50010437e9189f73e1747f617f0f3ba"><code>05110ba</code></a>
Issue <a
href="https://redirect.github.com/jetty/jetty.project/issues/13234">#13234</a>
- empty query entries should be retained for Fields and Servlet ...</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/de14739e3eb6e847498180e8c87592d5e953e316"><code>de14739</code></a>
Issue <a
href="https://redirect.github.com/jetty/jetty.project/issues/13300">#13300</a>
check ee namespace for resource-ref, resource-env-ref</li>
<li>Additional commits viewable in <a
href="https://github.com/jetty/jetty.project/compare/jetty-12.0.22...jetty-12.0.23">compare
view</a></li>
</ul>
</details>
<br />

Updates `org.eclipse.jetty.ee10:jetty-ee10-bom` from 12.0.22 to 12.0.23
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/jetty/jetty.project/releases">org.eclipse.jetty.ee10:jetty-ee10-bom's
releases</a>.</em></p>
<blockquote>
<h2>12.0.23</h2>
<h1>Special Thanks to the following Eclipse Jetty community members</h1>
<ul>
<li><a
href="https://github.com/maarouf-yassine"><code>@​maarouf-yassine</code></a>
(Maarouf Yassine)</li>
<li><a
href="https://github.com/kohlschuetter"><code>@​kohlschuetter</code></a>
(Dr. Christian Kohlschütter)</li>
</ul>
<h1>Changelog</h1>
<ul>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13303">#13303</a>
- Improved logging and exception handling in HTTP2Producer.</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13300">#13300</a>
- <code>o.e.j.plus.jndi.Resource</code>s declared in <code>eeX</code>
scope then linked via <code>&lt;resource-ref&gt;</code> or
<code>&lt;resource-env-ref&gt;</code> in web.xml not found</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13299">#13299</a>
- Race Condition in WebSocketConnection - Job failed:
java.lang.IllegalStateException: FILLING_AND_PARSING</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13274">#13274</a>
- 13287 Make <code>Environment</code> implementation thread-safe to
prevent <code>ConcurrentModificationException</code></li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13268">#13268</a>
- <code>charset=null</code> is automatically added when using
<code>Content-Type: application/problem+json</code> in Servlet ee10</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13266">#13266</a>
- Fix Typo in http.adoc (<a
href="https://github.com/maarouf-yassine"><code>@​maarouf-yassine</code></a>)</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13263">#13263</a>
- NPE from SslEndPoint.isInputShutdown</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13261">#13261</a>
- Improve handling of failed HTTP/2 requests</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13259">#13259</a>
- <code>org.eclipse.jetty.plus.jndi.Transaction</code> should support
<code>javax.naming.Referenceable</code> as a constructor option
too.</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13234">#13234</a>
- Regression in 12.0.21 on handling empty query parameters</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13232">#13232</a>
- Regression in ee9/ee8 getRequestDispatcher() exceptions</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13209">#13209</a>
- stop throwing ISE when complete() is called after abort()</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13201">#13201</a>
- Fix <code>ReadPendingException</code> warning</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13196">#13196</a>
- Download of large file may get stuck in an infinite loop (bug in
<code>IOResources.copy</code> / <code>Content.Source</code>) (<a
href="https://github.com/kohlschuetter"><code>@​kohlschuetter</code></a>)</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13190">#13190</a>
- Introduce ability to decode and/or canonicalize URIs in a
RewriteRule</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/12818">#12818</a>
- NPE with websocket java.lang.NullPointerException: Cannot invoke
&quot;org.eclipse.jetty.io.RetainableByteBuffer.hasRemaining()&quot;
because &quot;this.networkBuffer&quot; is null</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/jetty/jetty.project/commit/01a4119797e9cee53c974ae126cc316d0c8a533a"><code>01a4119</code></a>
Updating to version 12.0.23</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/030d5867e4562428103361b7d6e987f0707e3831"><code>030d586</code></a>
Fixing typo in release script</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/5ac211ce5abceb094255c3e802a7ea4189f2cc86"><code>5ac211c</code></a>
Race Condition in WebSocketConnection - Job failed:
java.lang.IllegalStateExc...</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/a5dcbd0df7925f55ffef9946e6aa4e46dafcfec9"><code>a5dcbd0</code></a>
Merge pull request <a
href="https://redirect.github.com/jetty/jetty.project/issues/13303">#13303</a>
from jetty/fix/jetty-12.0.x/improve-h2-producer-exc...</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/5b5f82d740dadf9f95f51c12c1e2d6500cd145c9"><code>5b5f82d</code></a>
Rework locked fields accesses in <code>SslConnection</code> (<a
href="https://redirect.github.com/jetty/jetty.project/issues/13265">#13265</a>)</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/87f982c9964117b36b4ff0d8278811013e97381a"><code>87f982c</code></a>
Merge pull request <a
href="https://redirect.github.com/jetty/jetty.project/issues/13301">#13301</a>
from jetty/jetty-12.0.x-13300-resource-ee-namespace</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/e179ee3a467e7f0793fa032ae92c47827f75ed6e"><code>e179ee3</code></a>
upgrade quiche to version 0.24.4</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/6d3f29260a40e669041293b1b18da3c9acf45017"><code>6d3f292</code></a>
Improved logging and exception handling in HTTP2Producer.</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/05110ba7c50010437e9189f73e1747f617f0f3ba"><code>05110ba</code></a>
Issue <a
href="https://redirect.github.com/jetty/jetty.project/issues/13234">#13234</a>
- empty query entries should be retained for Fields and Servlet ...</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/de14739e3eb6e847498180e8c87592d5e953e316"><code>de14739</code></a>
Issue <a
href="https://redirect.github.com/jetty/jetty.project/issues/13300">#13300</a>
check ee namespace for resource-ref, resource-env-ref</li>
<li>Additional commits viewable in <a
href="https://github.com/jetty/jetty.project/compare/jetty-12.0.22...jetty-12.0.23">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>