build(deps): bump jetty.version from 12.0.23 to 12.0.24 (#1024)
Bumps `jetty.version` from 12.0.23 to 12.0.24.
Updates `org.eclipse.jetty:jetty-bom` from 12.0.23 to 12.0.24
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/jetty/jetty.project/releases">org.eclipse.jetty:jetty-bom's
releases</a>.</em></p>
<blockquote>
<h2>12.0.24</h2>
<h1>Special Thanks to the following Eclipse Jetty community members</h1>
<ul>
<li><a href="https://github.com/afarber"><code>@​afarber</code></a>
(Alexander Farber)</li>
<li><a
href="https://github.com/maarouf-yassine"><code>@​maarouf-yassine</code></a>
(Maarouf Yassine)</li>
<li><a
href="https://github.com/trucnguyenlam"><code>@​trucnguyenlam</code></a>
(Truc Nguyen Lam)</li>
</ul>
<h1>Changelog</h1>
<ul>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13402">#13402</a>
- Use default constructor for Attributes.Mapped (<a
href="https://github.com/trucnguyenlam"><code>@​trucnguyenlam</code></a>)</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13386">#13386</a>
- Improve javadoc documentation for core API methods (<a
href="https://github.com/afarber"><code>@​afarber</code></a>)</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13384">#13384</a>
- fix mod file name for inclusion</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13368">#13368</a>
- Valid query sequences are still reported as violations to
ComplianceViolation.Listener</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13364">#13364</a>
- Deploy warnings for ee8 demos</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13363">#13363</a>
- Improve JSP scratch directory creation and error message.</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13356">#13356</a>
- Executing <code>--dry-run</code> via shell <code>$()</code> can fail
when certain JVM options are used.</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13354">#13354</a>
- Upgrade jasper-jsp 9.0.107, 10.1.43</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13348">#13348</a>
- jetty 12.0.x dependencies upgrade</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13336">#13336</a>
- HTTP/2 - Valid horizontal tab &quot;\t&quot; in http header is
coverted into &quot;?&quot;</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13324">#13324</a>
- ConnectionLimit doesn't work with WebSocket connections.</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13303">#13303</a>
- Improved logging and exception handling in HTTP2Producer.</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13300">#13300</a>
- <code>o.e.j.plus.jndi.Resource</code>s declared in <code>eeX</code>
scope then linked via <code>&lt;resource-ref&gt;</code> or
<code>&lt;resource-env-ref&gt;</code> in web.xml not found</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13299">#13299</a>
- Race Condition in WebSocketConnection - Job failed:
java.lang.IllegalStateException: FILLING_AND_PARSING</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13295">#13295</a>
- Fix comments in NamingEntry; add support for simple scope name</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13285">#13285</a>
- Upgrade quiche to version 0.24.4</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13284">#13284</a>
- jetty-openid library swallows provider errors when getting auth
code</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13274">#13274</a>
- <code>JettyWebSocketTest</code> sometimes fails with
<code>ConcurrentModificationException</code></li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13268">#13268</a>
- <code>charset=null</code> is automatically added when using
<code>Content-Type: application/problem+json</code> in Servlet ee10</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13266">#13266</a>
- Fix Typo in http.adoc (<a
href="https://github.com/maarouf-yassine"><code>@​maarouf-yassine</code></a>)</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13263">#13263</a>
- NPE from SslEndPoint.isInputShutdown</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13261">#13261</a>
- Improve handling of failed HTTP/2 requests</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13259">#13259</a>
- <code>org.eclipse.jetty.plus.jndi.Transaction</code> should support
<code>javax.naming.Referenceable</code> as a constructor option
too.</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13251">#13251</a>
- Jetty 12.0.x use our new release tools</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13234">#13234</a>
- Regression in 12.0.21 on handling empty query parameters</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13190">#13190</a>
- Introduce ability to decode and/or canonicalize URIs in a
RewriteRule</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/12818">#12818</a>
- NPE with websocket java.lang.NullPointerException: Cannot invoke
&quot;org.eclipse.jetty.io.RetainableByteBuffer.hasRemaining()&quot;
because &quot;this.networkBuffer&quot; is null</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/9794">#9794</a>
- Jetty 12 - jetty-ee9-proxy.xml broken</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/8867">#8867</a>
- Jetty maven plugin is not Maven toolchain aware</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/jetty/jetty.project/commit/20bd11c3ce5c2393599bf62873e94a3da7207886"><code>20bd11c</code></a>
Updating to version 12.0.24</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/1f185b6f9b44c51c3835a53ff01a579e2491ae6a"><code>1f185b6</code></a>
Call ResourceFactory.unregisterResourceFactory to clean up (<a
href="https://redirect.github.com/jetty/jetty.project/issues/13408">#13408</a>)</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/23589282254ea255f1f1cbff7c477f4cbbd22955"><code>2358928</code></a>
Use default constructor for Attributes.Mapped (<a
href="https://redirect.github.com/jetty/jetty.project/issues/13402">#13402</a>)</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/fd1bfd80edb18f71bb03134bf93f4c8032c43fed"><code>fd1bfd8</code></a>
Updating release checklist for new central.sonatype.com reality (<a
href="https://redirect.github.com/jetty/jetty.project/issues/13347">#13347</a>)</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/f684ac704b02a93dc837bb5bb01734709a612d52"><code>f684ac7</code></a>
Fixes <a
href="https://redirect.github.com/jetty/jetty.project/issues/13356">#13356</a>
- Executing --dry-run via shell $() can fail when certain JVM op...</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/368c1f89470aeb3ae91745f079fc979e56ae3766"><code>368c1f8</code></a>
Merge pull request <a
href="https://redirect.github.com/jetty/jetty.project/issues/13296">#13296</a>
from jetty/jetty-12.0.x-13284-openid-errorParams</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/8152ded307fda7e330aebf3bc842a23609bd8aaf"><code>8152ded</code></a>
PR <a
href="https://redirect.github.com/jetty/jetty.project/issues/13296">#13296</a>
- changes from review</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/e5b8eb8f9480ea72cb1bccd3fc9a62665ffba787"><code>e5b8eb8</code></a>
Improve javadoc documentation for core API methods (<a
href="https://redirect.github.com/jetty/jetty.project/issues/13386">#13386</a>)</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/cea7a7abbaf52f37a475dbefed49d29294a1c814"><code>cea7a7a</code></a>
fix mod file name for inclusion</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/06508c6833287c72d54aaea00e9a9f7314268987"><code>06508c6</code></a>
Merge remote-tracking branch 'origin/jetty-12.0.x' into
jetty-12.0.x-13284-op...</li>
<li>Additional commits viewable in <a
href="https://github.com/jetty/jetty.project/compare/jetty-12.0.23...jetty-12.0.24">compare
view</a></li>
</ul>
</details>
<br />

Updates `org.eclipse.jetty.ee10:jetty-ee10-bom` from 12.0.23 to 12.0.24
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/jetty/jetty.project/releases">org.eclipse.jetty.ee10:jetty-ee10-bom's
releases</a>.</em></p>
<blockquote>
<h2>12.0.24</h2>
<h1>Special Thanks to the following Eclipse Jetty community members</h1>
<ul>
<li><a href="https://github.com/afarber"><code>@​afarber</code></a>
(Alexander Farber)</li>
<li><a
href="https://github.com/maarouf-yassine"><code>@​maarouf-yassine</code></a>
(Maarouf Yassine)</li>
<li><a
href="https://github.com/trucnguyenlam"><code>@​trucnguyenlam</code></a>
(Truc Nguyen Lam)</li>
</ul>
<h1>Changelog</h1>
<ul>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13402">#13402</a>
- Use default constructor for Attributes.Mapped (<a
href="https://github.com/trucnguyenlam"><code>@​trucnguyenlam</code></a>)</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13386">#13386</a>
- Improve javadoc documentation for core API methods (<a
href="https://github.com/afarber"><code>@​afarber</code></a>)</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13384">#13384</a>
- fix mod file name for inclusion</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13368">#13368</a>
- Valid query sequences are still reported as violations to
ComplianceViolation.Listener</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13364">#13364</a>
- Deploy warnings for ee8 demos</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13363">#13363</a>
- Improve JSP scratch directory creation and error message.</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13356">#13356</a>
- Executing <code>--dry-run</code> via shell <code>$()</code> can fail
when certain JVM options are used.</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13354">#13354</a>
- Upgrade jasper-jsp 9.0.107, 10.1.43</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13348">#13348</a>
- jetty 12.0.x dependencies upgrade</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13336">#13336</a>
- HTTP/2 - Valid horizontal tab &quot;\t&quot; in http header is
coverted into &quot;?&quot;</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13324">#13324</a>
- ConnectionLimit doesn't work with WebSocket connections.</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13303">#13303</a>
- Improved logging and exception handling in HTTP2Producer.</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13300">#13300</a>
- <code>o.e.j.plus.jndi.Resource</code>s declared in <code>eeX</code>
scope then linked via <code>&lt;resource-ref&gt;</code> or
<code>&lt;resource-env-ref&gt;</code> in web.xml not found</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13299">#13299</a>
- Race Condition in WebSocketConnection - Job failed:
java.lang.IllegalStateException: FILLING_AND_PARSING</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13295">#13295</a>
- Fix comments in NamingEntry; add support for simple scope name</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13285">#13285</a>
- Upgrade quiche to version 0.24.4</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13284">#13284</a>
- jetty-openid library swallows provider errors when getting auth
code</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13274">#13274</a>
- <code>JettyWebSocketTest</code> sometimes fails with
<code>ConcurrentModificationException</code></li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13268">#13268</a>
- <code>charset=null</code> is automatically added when using
<code>Content-Type: application/problem+json</code> in Servlet ee10</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13266">#13266</a>
- Fix Typo in http.adoc (<a
href="https://github.com/maarouf-yassine"><code>@​maarouf-yassine</code></a>)</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13263">#13263</a>
- NPE from SslEndPoint.isInputShutdown</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13261">#13261</a>
- Improve handling of failed HTTP/2 requests</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13259">#13259</a>
- <code>org.eclipse.jetty.plus.jndi.Transaction</code> should support
<code>javax.naming.Referenceable</code> as a constructor option
too.</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13251">#13251</a>
- Jetty 12.0.x use our new release tools</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13234">#13234</a>
- Regression in 12.0.21 on handling empty query parameters</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/13190">#13190</a>
- Introduce ability to decode and/or canonicalize URIs in a
RewriteRule</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/12818">#12818</a>
- NPE with websocket java.lang.NullPointerException: Cannot invoke
&quot;org.eclipse.jetty.io.RetainableByteBuffer.hasRemaining()&quot;
because &quot;this.networkBuffer&quot; is null</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/9794">#9794</a>
- Jetty 12 - jetty-ee9-proxy.xml broken</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/8867">#8867</a>
- Jetty maven plugin is not Maven toolchain aware</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/jetty/jetty.project/commit/20bd11c3ce5c2393599bf62873e94a3da7207886"><code>20bd11c</code></a>
Updating to version 12.0.24</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/1f185b6f9b44c51c3835a53ff01a579e2491ae6a"><code>1f185b6</code></a>
Call ResourceFactory.unregisterResourceFactory to clean up (<a
href="https://redirect.github.com/jetty/jetty.project/issues/13408">#13408</a>)</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/23589282254ea255f1f1cbff7c477f4cbbd22955"><code>2358928</code></a>
Use default constructor for Attributes.Mapped (<a
href="https://redirect.github.com/jetty/jetty.project/issues/13402">#13402</a>)</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/fd1bfd80edb18f71bb03134bf93f4c8032c43fed"><code>fd1bfd8</code></a>
Updating release checklist for new central.sonatype.com reality (<a
href="https://redirect.github.com/jetty/jetty.project/issues/13347">#13347</a>)</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/f684ac704b02a93dc837bb5bb01734709a612d52"><code>f684ac7</code></a>
Fixes <a
href="https://redirect.github.com/jetty/jetty.project/issues/13356">#13356</a>
- Executing --dry-run via shell $() can fail when certain JVM op...</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/368c1f89470aeb3ae91745f079fc979e56ae3766"><code>368c1f8</code></a>
Merge pull request <a
href="https://redirect.github.com/jetty/jetty.project/issues/13296">#13296</a>
from jetty/jetty-12.0.x-13284-openid-errorParams</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/8152ded307fda7e330aebf3bc842a23609bd8aaf"><code>8152ded</code></a>
PR <a
href="https://redirect.github.com/jetty/jetty.project/issues/13296">#13296</a>
- changes from review</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/e5b8eb8f9480ea72cb1bccd3fc9a62665ffba787"><code>e5b8eb8</code></a>
Improve javadoc documentation for core API methods (<a
href="https://redirect.github.com/jetty/jetty.project/issues/13386">#13386</a>)</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/cea7a7abbaf52f37a475dbefed49d29294a1c814"><code>cea7a7a</code></a>
fix mod file name for inclusion</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/06508c6833287c72d54aaea00e9a9f7314268987"><code>06508c6</code></a>
Merge remote-tracking branch 'origin/jetty-12.0.x' into
jetty-12.0.x-13284-op...</li>
<li>Additional commits viewable in <a
href="https://github.com/jetty/jetty.project/compare/jetty-12.0.23...jetty-12.0.24">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>