build(deps): bump hibernate.version from 6.6.3.Final to 6.6.4.Final (#826)
Bumps `hibernate.version` from 6.6.3.Final to 6.6.4.Final.
Updates `org.hibernate.orm:hibernate-core` from 6.6.3.Final to
6.6.4.Final
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/hibernate/hibernate-orm/releases">org.hibernate.orm:hibernate-core's
releases</a>.</em></p>
<blockquote>
<h1>Hibernate ORM 6.6.4.Final released</h1>
<p>Today, we published a new release of Hibernate ORM 6.6:
6.6.4.Final.</p>
<p>You can find the full list of 6.6.4.Final changes <a
href="https://hibernate.atlassian.net/issues/?jql=project%20%3D%20HHH%20AND%20fixVersion%20%3D%206.6.4">here</a>.</p>
<h2>What's new</h2>
<p>This release introduces a few minor improvements as well as bug
fixes.</p>
<h2>Conclusion</h2>
<p>For additional details, see:</p>
<ul>
<li>the <a href="https://hibernate.org/orm/releases/6.6/">release
page</a></li>
<li>the <a
href="https://docs.jboss.org/hibernate/orm/6.6/migration-guide/migration-guide.html">Migration
Guide</a></li>
<li>the <a
href="https://docs.jboss.org/hibernate/orm/6.6/introduction/html_single/Hibernate_Introduction.html">Introduction
Guide</a></li>
<li>the <a
href="https://docs.jboss.org/hibernate/orm/6.6/userguide/html_single/Hibernate_User_Guide.html">User
Guide</a></li>
</ul>
<p>See also the following resources related to supported APIs:</p>
<ul>
<li>the <a
href="https://hibernate.org/community/compatibility-policy/">compatibility
policy</a></li>
<li>the <a
href="https://docs.jboss.org/hibernate/orm/6.6/incubating/incubating.txt">incubating
API report</a> (<code>@Incubating</code>)</li>
<li>the <a
href="https://docs.jboss.org/hibernate/orm/6.6/deprecated/deprecated.txt">deprecated
API report</a> (<code>@Deprecated</code> + <code>@Remove</code>)</li>
<li>the <a
href="https://docs.jboss.org/hibernate/orm/6.6/internals/internal.txt">internal
API report</a> (internal packages, <code>@Internal</code>)</li>
</ul>
<p>Visit the <a href="https://hibernate.org/community/">website</a> for
details on getting in touch with us.</p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/hibernate/hibernate-orm/blob/6.6.4/changelog.txt">org.hibernate.orm:hibernate-core's
changelog</a>.</em></p>
<blockquote>
<h2>Changes in 6.6.4.Final (December 18, 2024)</h2>
<p><a
href="https://hibernate.atlassian.net/projects/HHH/versions/32370">https://hibernate.atlassian.net/projects/HHH/versions/32370</a></p>
<p>** Bug
* [HHH-18949] - Hibernate Processor should not insert underscores within
uppercase names
* [HHH-18932] - Wrongly using FK column instead of PK when using joined
alias
* [HHH-18912] - ORM release process
* [HHH-18904] - Bytecode Enhancement fails with
UnsupportedEnhancementStrategy.FAIL for pre-persist method
* [HHH-18903] - Bytecode enhancement fails for entities that contain a
method named get
* [HHH-18872] - ConcreteProxy type not restored from 2LC when loading a
ManyToOne
* [HHH-18868] - Wrong behaviour of getAttribute method in impl. of
ManagedType when scattered id attributes are used in MappedSuperclass
* [HHH-18863] - jpamodelgen 6.6 performance issue in Eclipse IDE
* [HHH-18850] - createCountQuery with Hibernate 6.6.2
* [HHH-18709] - CriteriaUpdate involving JSON field containing Map<!--
raw HTML omitted --> results in SemanticException
* [HHH-18689] - 'FULL' query cache sometimes incomplete
* [HHH-18629] - Inconsistent column alias generated while result class
is used for placeholder
* [HHH-18583] - Joined + discriminator inheritance treat in where clause
not restricting to subtype
* [HHH-18384] - <a
href="https://github.com/JoinColumnsOrFormulas"><code>@​JoinColumnsOrFormulas</code></a>
broken
* [HHH-18274] - Problems with generics in queries; proposed partial
solution
* [HHH-17838] - <a
href="https://github.com/OneToOne"><code>@​OneToOne</code></a>
relationship + <a
href="https://github.com/Embeddable"><code>@​Embeddable</code></a> keys
+ FetchType.LAZY fail in most recent version
* [HHH-17612] - DefaultRevisionEntity: Illegal argument on static
metamodel field injection
* [HHH-14725] - Using a InputStream with BlobProxy and Envers results in
java.sql.SQLException: could not reset reader
* [HHH-13815] - TransientObjectException after merging a bidirectional
one-to-many with orphan deletion
* [HHH-13790] - Temporary session not being closed
* [HHH-13377] - Lazy loaded properties of bytecode enhanced entity are
left stale after refresh of entity</p>
<p>** Sub-task
* [HHH-18369] - Support Informix matches() function
* [HHH-18367] - Informix sum on case expression error
* [HHH-18365] - Informix function bit_length() error
* [HHH-18364] - Informix function locate() error
* [HHH-18363] - Informix component nullness check error
* [HHH-18362] - Informix function substring() error
* [HHH-18361] - Informix current_time error
* [HHH-18360] - Informix function str() error</p>
<p>** Task
* [HHH-18917] - Follow all of the JavaBeans rules in
enhance/internal/bytebuddy/EnhancerImpl when checking if a class can be
enhanced
* [HHH-18906] - Allow specifying UnsupportedEnhancementStrategy for
Hibernate testing</p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/hibernate/hibernate-orm/commit/c22c25b7d7743ae89ae1f82a6ae1e2ff7802ed17"><code>c22c25b</code></a>
Pre-steps for release : <code>6.6.4.Final</code></li>
<li><a
href="https://github.com/hibernate/hibernate-orm/commit/0afa7458cafd5d0dd5d240ac62ac69534fe17a5b"><code>0afa745</code></a>
HHH-18912 - ORM release process</li>
<li><a
href="https://github.com/hibernate/hibernate-orm/commit/8956c0a585e8e9edc205a490a1a9a372dcf1bb8f"><code>8956c0a</code></a>
HHH-18912 - ORM release process</li>
<li><a
href="https://github.com/hibernate/hibernate-orm/commit/376dbb17345410fd4620afd580608822d1b8e9ed"><code>376dbb1</code></a>
Try fixing publishing</li>
<li><a
href="https://github.com/hibernate/hibernate-orm/commit/9c4d33b00d512eb558aa39da914df57ca3d3b71d"><code>9c4d33b</code></a>
Various release script fixes</li>
<li><a
href="https://github.com/hibernate/hibernate-orm/commit/e685425fdbc8e3c2ed8214544d2162b697e24aca"><code>e685425</code></a>
don't generate &quot;auxiliary&quot; members for Jakarta Data static
metamodel</li>
<li><a
href="https://github.com/hibernate/hibernate-orm/commit/103b2f80615d93d7774ac1be856fadea5d0a4b7f"><code>103b2f8</code></a>
HHH-14725 Fixed test</li>
<li><a
href="https://github.com/hibernate/hibernate-orm/commit/0b61cc3d3a1fa3e2eb153ec4fe6c66dd8aedd75c"><code>0b61cc3</code></a>
HHH-14725 Fix reset handling on BlobProxy</li>
<li><a
href="https://github.com/hibernate/hibernate-orm/commit/0b28e2c45de895e7fe0d896a649d405740cb555e"><code>0b28e2c</code></a>
HHH-14725 Fixed test</li>
<li><a
href="https://github.com/hibernate/hibernate-orm/commit/6300c34a2c28efae1f120216b18088f3350883ac"><code>6300c34</code></a>
HHH-14725 Adjust test to use byte array, update Javadoc</li>
<li>Additional commits viewable in <a
href="https://github.com/hibernate/hibernate-orm/compare/6.6.3...6.6.4">compare
view</a></li>
</ul>
</details>
<br />

Updates `org.hibernate.orm:hibernate-micrometer` from 6.6.3.Final to
6.6.4.Final
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/hibernate/hibernate-orm/releases">org.hibernate.orm:hibernate-micrometer's
releases</a>.</em></p>
<blockquote>
<h1>Hibernate ORM 6.6.4.Final released</h1>
<p>Today, we published a new release of Hibernate ORM 6.6:
6.6.4.Final.</p>
<p>You can find the full list of 6.6.4.Final changes <a
href="https://hibernate.atlassian.net/issues/?jql=project%20%3D%20HHH%20AND%20fixVersion%20%3D%206.6.4">here</a>.</p>
<h2>What's new</h2>
<p>This release introduces a few minor improvements as well as bug
fixes.</p>
<h2>Conclusion</h2>
<p>For additional details, see:</p>
<ul>
<li>the <a href="https://hibernate.org/orm/releases/6.6/">release
page</a></li>
<li>the <a
href="https://docs.jboss.org/hibernate/orm/6.6/migration-guide/migration-guide.html">Migration
Guide</a></li>
<li>the <a
href="https://docs.jboss.org/hibernate/orm/6.6/introduction/html_single/Hibernate_Introduction.html">Introduction
Guide</a></li>
<li>the <a
href="https://docs.jboss.org/hibernate/orm/6.6/userguide/html_single/Hibernate_User_Guide.html">User
Guide</a></li>
</ul>
<p>See also the following resources related to supported APIs:</p>
<ul>
<li>the <a
href="https://hibernate.org/community/compatibility-policy/">compatibility
policy</a></li>
<li>the <a
href="https://docs.jboss.org/hibernate/orm/6.6/incubating/incubating.txt">incubating
API report</a> (<code>@Incubating</code>)</li>
<li>the <a
href="https://docs.jboss.org/hibernate/orm/6.6/deprecated/deprecated.txt">deprecated
API report</a> (<code>@Deprecated</code> + <code>@Remove</code>)</li>
<li>the <a
href="https://docs.jboss.org/hibernate/orm/6.6/internals/internal.txt">internal
API report</a> (internal packages, <code>@Internal</code>)</li>
</ul>
<p>Visit the <a href="https://hibernate.org/community/">website</a> for
details on getting in touch with us.</p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/hibernate/hibernate-orm/blob/6.6.4/changelog.txt">org.hibernate.orm:hibernate-micrometer's
changelog</a>.</em></p>
<blockquote>
<h2>Changes in 6.6.4.Final (December 18, 2024)</h2>
<p><a
href="https://hibernate.atlassian.net/projects/HHH/versions/32370">https://hibernate.atlassian.net/projects/HHH/versions/32370</a></p>
<p>** Bug
* [HHH-18949] - Hibernate Processor should not insert underscores within
uppercase names
* [HHH-18932] - Wrongly using FK column instead of PK when using joined
alias
* [HHH-18912] - ORM release process
* [HHH-18904] - Bytecode Enhancement fails with
UnsupportedEnhancementStrategy.FAIL for pre-persist method
* [HHH-18903] - Bytecode enhancement fails for entities that contain a
method named get
* [HHH-18872] - ConcreteProxy type not restored from 2LC when loading a
ManyToOne
* [HHH-18868] - Wrong behaviour of getAttribute method in impl. of
ManagedType when scattered id attributes are used in MappedSuperclass
* [HHH-18863] - jpamodelgen 6.6 performance issue in Eclipse IDE
* [HHH-18850] - createCountQuery with Hibernate 6.6.2
* [HHH-18709] - CriteriaUpdate involving JSON field containing Map<!--
raw HTML omitted --> results in SemanticException
* [HHH-18689] - 'FULL' query cache sometimes incomplete
* [HHH-18629] - Inconsistent column alias generated while result class
is used for placeholder
* [HHH-18583] - Joined + discriminator inheritance treat in where clause
not restricting to subtype
* [HHH-18384] - <a
href="https://github.com/JoinColumnsOrFormulas"><code>@​JoinColumnsOrFormulas</code></a>
broken
* [HHH-18274] - Problems with generics in queries; proposed partial
solution
* [HHH-17838] - <a
href="https://github.com/OneToOne"><code>@​OneToOne</code></a>
relationship + <a
href="https://github.com/Embeddable"><code>@​Embeddable</code></a> keys
+ FetchType.LAZY fail in most recent version
* [HHH-17612] - DefaultRevisionEntity: Illegal argument on static
metamodel field injection
* [HHH-14725] - Using a InputStream with BlobProxy and Envers results in
java.sql.SQLException: could not reset reader
* [HHH-13815] - TransientObjectException after merging a bidirectional
one-to-many with orphan deletion
* [HHH-13790] - Temporary session not being closed
* [HHH-13377] - Lazy loaded properties of bytecode enhanced entity are
left stale after refresh of entity</p>
<p>** Sub-task
* [HHH-18369] - Support Informix matches() function
* [HHH-18367] - Informix sum on case expression error
* [HHH-18365] - Informix function bit_length() error
* [HHH-18364] - Informix function locate() error
* [HHH-18363] - Informix component nullness check error
* [HHH-18362] - Informix function substring() error
* [HHH-18361] - Informix current_time error
* [HHH-18360] - Informix function str() error</p>
<p>** Task
* [HHH-18917] - Follow all of the JavaBeans rules in
enhance/internal/bytebuddy/EnhancerImpl when checking if a class can be
enhanced
* [HHH-18906] - Allow specifying UnsupportedEnhancementStrategy for
Hibernate testing</p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/hibernate/hibernate-orm/commit/c22c25b7d7743ae89ae1f82a6ae1e2ff7802ed17"><code>c22c25b</code></a>
Pre-steps for release : <code>6.6.4.Final</code></li>
<li><a
href="https://github.com/hibernate/hibernate-orm/commit/0afa7458cafd5d0dd5d240ac62ac69534fe17a5b"><code>0afa745</code></a>
HHH-18912 - ORM release process</li>
<li><a
href="https://github.com/hibernate/hibernate-orm/commit/8956c0a585e8e9edc205a490a1a9a372dcf1bb8f"><code>8956c0a</code></a>
HHH-18912 - ORM release process</li>
<li><a
href="https://github.com/hibernate/hibernate-orm/commit/376dbb17345410fd4620afd580608822d1b8e9ed"><code>376dbb1</code></a>
Try fixing publishing</li>
<li><a
href="https://github.com/hibernate/hibernate-orm/commit/9c4d33b00d512eb558aa39da914df57ca3d3b71d"><code>9c4d33b</code></a>
Various release script fixes</li>
<li><a
href="https://github.com/hibernate/hibernate-orm/commit/e685425fdbc8e3c2ed8214544d2162b697e24aca"><code>e685425</code></a>
don't generate &quot;auxiliary&quot; members for Jakarta Data static
metamodel</li>
<li><a
href="https://github.com/hibernate/hibernate-orm/commit/103b2f80615d93d7774ac1be856fadea5d0a4b7f"><code>103b2f8</code></a>
HHH-14725 Fixed test</li>
<li><a
href="https://github.com/hibernate/hibernate-orm/commit/0b61cc3d3a1fa3e2eb153ec4fe6c66dd8aedd75c"><code>0b61cc3</code></a>
HHH-14725 Fix reset handling on BlobProxy</li>
<li><a
href="https://github.com/hibernate/hibernate-orm/commit/0b28e2c45de895e7fe0d896a649d405740cb555e"><code>0b28e2c</code></a>
HHH-14725 Fixed test</li>
<li><a
href="https://github.com/hibernate/hibernate-orm/commit/6300c34a2c28efae1f120216b18088f3350883ac"><code>6300c34</code></a>
HHH-14725 Adjust test to use byte array, update Javadoc</li>
<li>Additional commits viewable in <a
href="https://github.com/hibernate/hibernate-orm/compare/6.6.3...6.6.4">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>